name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  install-and-test:
    # Job name is Greeting
    name: Install and test
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm install
      - name: Run tests
        run: echo 'Test'
  job_2:
    # Job name is Greeting
    name: Greeting from job_2
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
